apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres