apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: yogender027/flask-app:0.0.3 # Replace with your image name
        env:
        - name: MPLCONFIGDIR
          value: "/tmp"  # Set MPLCONFIGDIR to /tmp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp  # Mounting the /tmp directory to avoid permission issues
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30004
  type: NodePort
