apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc  # Name of the PVC
  namespace: db  # Replace with your actual namespace
spec:
  accessModes:
    - ReadWriteOnce  # Must match the access mode of the PV
  resources:
    requests:
      storage: 2Gi  # Must match the size of the PV
  storageClassName: local-storage